The version of bundler used in the Travis CI builds is 1.7.6, which is from Nov 2014 and causes issues, such as:
NoMethodError: undefined method `spec' for nil:NilClass
An error occurred while installing que-testing (0.1.1), and Bundler cannot